### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by s1162276945** [CrowdDynamicsLab/NCF-GAN#1]
dataset = sys.argv[1]
IndexError: list index out of range

**Comment by aditk2** [comment]
Thank you for raising the issue. The command line argument is the path to the dataset folder.

**Comment by s1162276945** [comment]
> The command line argument is the path to the dataset folder

yes, I can run it on Linux system now, thank you.

**Comment by s1162276945** [comment]
> > The command line argument is the path to the dataset folder
> 
> yes, I can run it when I use the command line now, thank you.
